### ISSUE TITLE
在安装和使用中的问题

### ISSUE THREAD

**Issue by GAS0968** [whaleluo/electron-print-preview#1]
您好作者，依赖初衷非常好，但在使用中有一些问题，目前还没跑起来o(╥﹏╥)o
1、createWindow使用问题：
```typescript
const {printPreview}  =  require("electron-print-preview");

async function createWindow() {
    PrintPreview.getIntance().createPdfWindow(undefined,{
        htmlString:`<style>h1{color: #42b983}</style> <h1>hello world !</h1>`
    })
}
``` 
应为
```typescript
const {printPreview}  =  require("electron-print-preview");

async function createWindow () {
  printPreview.default.getIntance().createPdfWindow(undefined, {
    htmlString: '<style>h1{color: #42b983}</style> <h1>hello world !</h1>'
  })
}
``` 
2、点击打印过程中，预览窗口右侧选择区无法加载，主进程报错：
```
(node:28368) electron: Failed to load URL: file:///E:/test/vue2electron_project2/dist_electron/index.html with error: ERR_FILE_NOT_FOUND
``` 
![image](https://github.com/whaleluo/electron-print-preview/assets/69947234/bb3d9c95-7e38-4470-a345-cc09b770512f)

**Comment by whaleluo** [comment]
1、感谢指摘，之前代码改动，忘记更新ReadMe了。
2、右边没有加载是因为找不到对于的html文件。（html文件在electron-print-preview这个包里面）
如果你是webpack打包，需要配置
`  externals: {
    'electron-print-preview': 'require("electron-print-preview")'
  }`
3、这个实际还有一些性能问题。还在优化中。可能过段时间会提交

**Comment by GAS0968** [comment]
2、我在vue.config.js中配置的有，实际还是不行，需要在webpack.config.js中吗？
```typescript
const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  transpileDependencies: true,
  configureWebpack: {
    externals: {
      'electron-print-preview': 'require("electron-print-preview")'
    }
  }
})

``` 
3、期待，哈哈，应该挺好用的

**Comment by whaleluo** [comment]
不太清楚你项目结构。
你这个配置是应该只是打包vue前端项目。并没有打包electron的代码
我之前开发是用vue-cli-plugin-electron-builde。这个脚手架是可以打包vue和electron的代码

**Comment by GAS0968** [comment]
我也是用的vue-cli-plugin-electron-builde哈，改了配置已经跑起来了，Thanks大佬
目前还有最后一个问题，变更纸张尺寸无效，不管变哪个最后打印出来的都是A4，不知道是不是一个bug...

**Comment by whaleluo** [comment]
这个可能和electron版本有关。看你electron版本是多少，现在最新的electron的webContents.print方法变化比较大。
你可能要看着源码改一下相关参数

**Comment by whaleluo** [comment]
这个包本身就是用electron把htm打印为pdf文件，然后渲染到browserWindow里面。每次改变纸张都会重复这个过程
