### ISSUE TITLE
这个包本身就是用electron把htm打印为pdf文件，然后渲染到browserWindow里面。每次改变纸张都会重复这个过程

### ISSUE THREAD

**Issue by GAS0968** [whaleluo/electron-print-preview#2]
这个包本身就是用electron把htm打印为pdf文件，然后渲染到browserWindow里面。每次改变纸张都会重复这个过程

_Originally posted by @whaleluo in https://github.com/whaleluo/electron-print-preview/issues/1#issuecomment-1614071737_

**Comment by GAS0968** [comment]
不好意思老师，我这不清楚操作不小心新建了个issue，那就在这里问吧。
我这里用的electron版本和您是一样的，也是 13.0.0，但是在打印预览页面中，页面尺寸选择A5之后实际不生效，打印出来的还是A4，我看了一遍您的源码，应该是没有问题的。
我自己使用webContents.print写了个demo，直接传入A5，实际打印出来的也还是A4。
很奇怪，我怀疑是不是electron的这个api有问题，您在测试过程中能够打印出来A5的内容吗？

**Comment by whaleluo** [comment]
是可以正常打印A5纸张（A3、A4、A5我这边都试过没问题)。
你可以看下最新版本，重新优化了下，已经测过（依赖electron@24.1.2）

**Comment by GAS0968** [comment]
不敢切换electron版本，涉及东西太多了，我再试试，不行就先导出pdf再在pdf里打印吧o(╥﹏╥)o
我查到一个electron的issue（[electron/issue](https://github.com/electron/electron/issues/31705)），也有反馈这个问题，感觉可能和打印机也有关系o(╯□╰)o
